
import React from 'react';
import Button from '../components/Button';
import { ArrowLeftIcon } from '../components/icons/ArrowLeftIcon';

interface DisclaimerProps {
    onBack: () => void;
}

const Disclaimer: React.FC<DisclaimerProps> = ({ onBack }) => {
    return (
        <div className="container mx-auto max-w-4xl text-slate-300 py-8">
            <Button onClick={onBack} className="mb-8 bg-slate-700 hover:bg-slate-600">
                <ArrowLeftIcon className="w-5 h-5 mr-2" />
                Back to App
            </Button>
            <div className="space-y-6 bg-slate-800/50 p-8 rounded-2xl border border-slate-700">
                <h1 className="text-3xl font-bold text-sky-400">Disclaimer</h1>
                <p>Last updated: {new Date().toLocaleDateString()}</p>

                <h2 className="text-2xl font-semibold text-slate-100 pt-4">General Information</h2>
                <p>The AI Virtual Try-On application provides a simulated image for entertainment and informational purposes only. The results are generated by an artificial intelligence model and should be considered an artistic representation, not a perfectly accurate depiction.</p>

                <h2 className="text-2xl font-semibold text-slate-100 pt-4">Accuracy of Results</h2>
                <p>The quality and accuracy of the generated image depend on several factors, including the quality, lighting, pose, and resolution of the uploaded images. We make no guarantees regarding the accuracy of the fit, color, texture, or appearance of the clothing in the final image.</p>
                 <ul className="list-disc list-inside space-y-2 pl-4">
                    <li>The AI may produce unexpected or imperfect results.</li>
                    <li>The generated image is a simulation and may not reflect how the outfit would look in real life.</li>
                    <li>The service is provided "as is" without any warranties, express or implied.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-slate-100 pt-4">Limitation of Liability</h2>
                <p>In no event shall AI Virtual Try-On Studio, nor any of its officers, directors, and employees, be held liable for anything arising out of or in any way connected with your use of this application. We are not responsible for any decisions made based on the output of this service.</p>
                
                <h2 className="text-2xl font-semibold text-slate-100 pt-4">User Responsibility</h2>
                <p>You are solely responsible for the images you upload. You must ensure you have the right to use and upload these images and that they do not violate any laws or third-party rights.</p>
            </div>
        </div>
    );
};

export default Disclaimer;
